package Partes;


import Menus.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Liseth
 */
public class Partes extends javax.swing.JFrame {

    /**
     * Creates new form Partes
     */
    public Menu ventanaM;
    public CrearVentanasPartes ventanas;
    public Partes() {
        ventanas= new CrearVentanasPartes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        r_bor = new javax.swing.JRadioButton();
        r_ins = new javax.swing.JRadioButton();
        r_asop = new javax.swing.JRadioButton();
        r_asoa = new javax.swing.JRadioButton();
        r_act = new javax.swing.JRadioButton();
        r_lis = new javax.swing.JRadioButton();
        b_con = new javax.swing.JButton();
        b_atr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Partes");

        r_bor.setText("Borrar");
        r_bor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_borMouseClicked(evt);
            }
        });
        r_bor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_borActionPerformed(evt);
            }
        });

        r_ins.setText("Insertar");
        r_ins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_insMouseClicked(evt);
            }
        });

        r_asop.setText("Asociar con proveedores");
        r_asop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_asopMouseClicked(evt);
            }
        });
        r_asop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_asopActionPerformed(evt);
            }
        });

        r_asoa.setText("Asociar con tipo de automóviles");
        r_asoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_asoaMouseClicked(evt);
            }
        });
        r_asoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_asoaActionPerformed(evt);
            }
        });

        r_act.setText("Actualizar precios de proveedores");
        r_act.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_actMouseClicked(evt);
            }
        });
        r_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_actActionPerformed(evt);
            }
        });

        r_lis.setText("Listar");
        r_lis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_lisMouseClicked(evt);
            }
        });

        b_con.setText("Continuar");
        b_con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_conMouseClicked(evt);
            }
        });

        b_atr.setText("Atrás");
        b_atr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_atrMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r_asop)
                            .addComponent(r_bor)
                            .addComponent(r_asoa)
                            .addComponent(r_act)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r_lis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                                .addComponent(b_atr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_con)))))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(r_ins)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addComponent(r_bor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_asop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_asoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_act)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_lis)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_con)
                    .addComponent(b_atr))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(r_ins)
                    .addContainerGap(202, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_borActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_borActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_borActionPerformed

    private void r_asopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_asopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_asopActionPerformed

    private void r_asoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_asoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_asoaActionPerformed

    private void r_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_actActionPerformed

    private void b_atrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_atrMouseClicked
        // TODO add your handling code here:
        
        ventanaM.setVisible(true);
        this.dispose();
        r_ins.setSelected(false);
        r_bor.setSelected(false);
        r_asop.setSelected(false);
        r_asoa.setSelected(false);
        r_act.setSelected(false);
        r_lis.setSelected(false);
    }//GEN-LAST:event_b_atrMouseClicked

    private void r_insMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_insMouseClicked
        r_bor.setSelected(false);
        r_asop.setSelected(false);
        r_asoa.setSelected(false);
        r_act.setSelected(false);
        r_lis.setSelected(false);
    }//GEN-LAST:event_r_insMouseClicked

    private void r_borMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_borMouseClicked
        r_ins.setSelected(false);
        r_asop.setSelected(false);
        r_asoa.setSelected(false);
        r_act.setSelected(false);
        r_lis.setSelected(false);
    }//GEN-LAST:event_r_borMouseClicked

    private void r_asopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_asopMouseClicked
        r_ins.setSelected(false);
        r_bor.setSelected(false);
        r_asoa.setSelected(false);
        r_act.setSelected(false);
        r_lis.setSelected(false);
    }//GEN-LAST:event_r_asopMouseClicked

    private void r_asoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_asoaMouseClicked
        r_ins.setSelected(false);
        r_bor.setSelected(false);
        r_asop.setSelected(false);
        r_act.setSelected(false);
        r_lis.setSelected(false);
    }//GEN-LAST:event_r_asoaMouseClicked

    private void r_actMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_actMouseClicked
        r_ins.setSelected(false);
        r_bor.setSelected(false);
        r_asop.setSelected(false);
        r_asoa.setSelected(false);
        r_lis.setSelected(false);
    }//GEN-LAST:event_r_actMouseClicked

    private void r_lisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_lisMouseClicked
       r_ins.setSelected(false);
        r_bor.setSelected(false);
        r_asop.setSelected(false);
        r_asoa.setSelected(false);
        r_act.setSelected(false);
    }//GEN-LAST:event_r_lisMouseClicked

    private void b_conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_conMouseClicked
        if(r_ins.isSelected()==true){
            ventanas.getVentanaIP().setVisible(true);
            ventanas.getVentanaIP().ventanaP = this;
            this.dispose();
        }
        else if(r_bor.isSelected()==true){
            ventanas.getVentanaBP().setVisible(true);
            ventanas.getVentanaBP().ventanaP = this;
            this.dispose();
        }
        else if(r_lis.isSelected()==true){
            ventanas.getVentanaLP().setVisible(true);
            ventanas.getVentanaLP().ventanaP = this;
            this.dispose();
        }
        else if(r_asop.isSelected()){
            ventanas.getVentanaAsociarParteProvedor().setVisible(true);
            ventanas.getVentanaAsociarParteProvedor().ventanaP = this;
            this.dispose();
        }
        else if(r_act.isSelected()){
            ventanas.getActualizarPreciosParte().setVisible(true);
            ventanas.getActualizarPreciosParte().ventanaP = this;
            this.dispose();
        }
        else if(r_asoa.isSelected()){
            ventanas.getVentanaAsociarParteVehiculo().setVisible(true);
            ventanas.getVentanaAsociarParteVehiculo().ventanaP = this;
            this.dispose();
        }
    }//GEN-LAST:event_b_conMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_atr;
    private javax.swing.JButton b_con;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton r_act;
    private javax.swing.JRadioButton r_asoa;
    private javax.swing.JRadioButton r_asop;
    private javax.swing.JRadioButton r_bor;
    private javax.swing.JRadioButton r_ins;
    private javax.swing.JRadioButton r_lis;
    // End of variables declaration//GEN-END:variables
}
